"""add_injury_reporting_fields_to_timelog

Revision ID: 77916761cc69
Revises: 
Create Date: 2025-06-04 11:14:03.196535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77916761cc69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - AND ADJUSTED! ###
    # op.drop_table('timelog')
    op.add_column('time_log', sa.Column('injured_at_work', sa.Boolean(), nullable=True))
    op.add_column('time_log', sa.Column('safety_signature', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.create_index('ix_time_log_injured_at_work', 'time_log', ['injured_at_work'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - AND ADJUSTED! ###
    op.drop_index('ix_time_log_injured_at_work', table_name='time_log')
    op.drop_column('time_log', 'safety_signature')
    op.drop_column('time_log', 'injured_at_work')
    # op.create_table('timelog', ... )
    # ### end Alembic commands ###
