"""MANUAL_add_original_dealership_id

Revision ID: 7f0819b71ebb
Revises: 77916761cc69
Create Date: 2025-06-23 13:16:35.340051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f0819b71ebb'
down_revision: Union[str, None] = '77916761cc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_time_changes', sa.Column('original_dealership_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_time_changes', 'original_dealership_id')
    # ### end Alembic commands ###
